name: money_management
description: "Money Management"
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  url_strategy: ^0.3.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  get: ^4.6.6
  intl: ^0.19.0
  get_storage: ^2.1.1
  toastification: ^2.3.0
  quickalert: ^1.1.0
  google_fonts: ^6.2.1
  loader_overlay: ^4.0.2+1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
